### ISSUE TITLE
Blank screen on HTC Explorer

### ISSUE THREAD

**Issue by grassick** [mWater/app-v3#451]
HTC Explorer phones open the app, it says "loading app" and then goes to a blank screen - they've force closed the app, restarted the phones, but still getting same response.

Re-install from Google Play has no effect. Started in 3.15.1, it seems.

**Comment by grassick** [comment]
@rachelmwater Did they already have a working version on the phone before? Or was this a problem from the first install?

**Comment by rachelmwater** [comment]
No they've had it working for a week or two - only had the problem today 18Feb

**Comment by grassick** [comment]
Upgraded cordova since then. See http://stackoverflow.com/questions/26465832/typeerror-cannot-set-property-connection-of-navigator-in-console-when-upgra which happens on my old IDEOS (Android 2.3.6)

**Comment by grassick** [comment]
Caused by https://github.com/wycats/handlebars.js/issues/965 on Android 2.3.6 Infuse.

**Comment by grassick** [comment]
https://issues.apache.org/jira/browse/CB-7868 has a patch for another issue:

```
 function clobber(obj, key, value) {
     exports.replaceHookForTesting(obj, key);
-    obj[key] = value;
+    var needsProperty = false;
+    try {
+        obj[key] = value;
+    } catch (e) {
+        needsProperty = true;
+    }
     // Getters can only be overridden by getters.
-    if (obj[key] !== value) {
+    if (needsProperty || obj[key] !== value) {
         utils.defineGetter(obj, key, function() {
             return value;
         });
```
