### ISSUE TITLE
Internal error on chrome for iOS

### ISSUE THREAD

**Issue by rocketboy76** [mWater/app-v3#482]
When I open app.mwater.co in chrome for iOS, I get the error below at the login screen.

![2015-08-22 07 38 24](https://cloud.githubusercontent.com/assets/1239663/9422871/6d0a25cc-48a8-11e5-9f3e-1ff6381eb65f.png)

**Comment by grassick** [comment]
http://stackoverflow.com/questions/26483541/referenceerror-cant-find-variable-gcrweb
